### PR TITLE
『:bug:』Fix: File Name of Jar file when invoked

### LINKED ISSUE #7: I see great potential for this tool in emacs ecosystem, I would  love to work as contributor
Found a bug where the name of the jar is missmatched

### PR DESCRIPTION
**Pull request by larebsyed**
The download name is different from the running name

fixes #7

### CODE REVIEW

**Comment by larebsyed** [comment]
@ag91 Here I created my first PR with something I thought was by mistake. Please take a look

**Comment by ag91** [comment]
@larebsyed very good, could you give a look to my comment? I think that is a typo.

**Comment by larebsyed** [comment]
I think you haven't posted the comment yet, as I don't see it

**Comment by larebsyed** [comment]
@ag91 but I think I realized the mistake and fixed it

**Comment by ag91** [comment]
amazing, indeed that was the issue! Yes, lol, I am terrible with this GitHub review mechanism: I comment but then I also need to submit the review otherwise you do not see it.

**Pull request merged**
