### PR TITLE
Port helper python script to Python 3

### PR DESCRIPTION
**Pull request by BlankSpruce**
Python 2 is no longer supported anymore since last year ([Python 2.7 Countdown](https://pythonclock.org/)) so I've ported helper script to Python 3. In some distributions, manjaro for instance, `python` is not necessarily pointing to `python2` hence the proposed change. Additionally I've reformatted code with black, which I can advertise as a nice and easy-to-use formatter, and made some statements pythonic. This script might require some further work but I've stopped at this point.

You might also consider extracting other inlined files.

### CODE REVIEW

**Comment by ag91** [comment]
hi @BlankSpruce, thanks a lot for sharing this! I will take a little bit of time in reviewing this, because I have another bit of functionality that I am about to release which also uses a python 2.7 script. I need to really understand the differences between version 2 and 3 :P
I will look into it in the next few days. Happy 2021 meanwhile!

**Comment by BlankSpruce** [comment]
Usually it's safe bet to simply invoke `2to3` on the file (there are caveats but it's not the thing in this case). That being said once you publish this new functionality I'll update this PR.

**Comment by ag91** [comment]
I have added the new functionality! And I have followed your suggestion (nice `2to3`), so the new python script is already version 3: thanks @BlankSpruce .
I did not put in a dedicated directory because I did not want to create problems with your PR: I am going to try it out and merge it in a bit.

**Comment by BlankSpruce** [comment]
I've rebased and split the change into more commits to make review slightly easier.

**Comment by ag91** [comment]
thanks again! It looks to me, and I also learned about destructuring in python :D

**Pull request merged**
